### ISSUE TITLE
Error	 CS0117	'Program' does not contain a definition for 'Settings'	HashServer

### ISSUE THREAD

**Issue by dimpol** [K2/HashServer#1]
During Build I come across the following.
Error	 CS0117	'Program' does not contain a definition for 'Settings'	HashServer
Any ideas?

**Comment by K2** [comment]
Could be I  messed up a checkin, I'll try a fresh checkout.

**Comment by dimpol** [comment]
@K2 
Unfortunately I cannot get HashServer to run properly on VS 2017.  Basically it is beyond my level, to follow the code and understand how I should proceed in general. Closing the issue to not spend your time further.

**Comment by K2** [comment]
Hey no worries, I did get some time to test out some fixes that should make things easier to run on your own.  I'll take a stab at some documentation also.  Let me know if this helps you out. https://github.com/K2/HashServer/commit/baad781d480946978a89a760574e9e1787f8a8a1

**Comment by dimpol** [comment]
@K2 I really appreciate the time you spent to make those adjustments.

Since i would really like to test your code, can you please give me in a few lines the steps that i should take to test your code (run this first, run that then...).

For example how to first create that golden image and then how to test how any code injection.
